default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: sansaru_development
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost

test: &test
  <<: *development
  database: sansaru_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
cucumber:
  <<: *test