default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: sanSaru
  username: postgres
  password: k4m4l30n
  host: localhost

test: &test
  <<: *development
  database: sansaru_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
cucumber:
  <<: *test
